version: "3"

services:

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config/promtail/:/etc/promtail/
    command: -config.file=/etc/promtail/config.yaml

