server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://35.190.156.201:3004/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: jsonlogs
          __path__: /etc/promtail/*.json
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: devlogs
          __path__: /etc/promtail/*.log
