server:
   http_listen_port: 9080
   grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/api/prom/push
  
scrape_configs:
- job_name: myapp
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: ./*.json
  pipeline_stages:
    - json:
        expressions:
          output: log
          stream: '"grpc.stream"'
          timestamp: time


      # we can add more labels for get logs
